### PR TITLE
From boilerplate

### PR DESCRIPTION
**Pull request by onelson**
This change aims to wedge the current in-progress app into the project boilerplate found here:
https://github.com/chentsulin/electron-react-boilerplate

So, there was a BUNCH of ground to cover to get this working. It's barely tested in that I don't have the oauth keys required to actually try out the auth flow, but I've got:
- some scaffolding in there for redux and react router
- wired up all the dev tool goodies
- got the server code going through babel so you can use some nicer sytnax
- live live live live live reloading (I'm telling you, you'll only need the edge of your seat)
- single package.json for the whole deal

Some stuff I know I missed:
- a bunch of initialization stuff you had in your express server, should be a simple enough merge, but omitted since much of it seemed already covered by default
- port customization (currently the server port is hardcoded, but should be added as a global via webpack's define plugin, probably looking to env for an override)
- testing the auth flow (I need to register somewhere to get keys?)

### CODE REVIEW

**Comment by bryanveloso** [comment]
You can create an app to get keys here: https://www.twitch.tv/settings/connections

Thanks for the work so far! I'll give it a test in the morning.

**Comment by onelson** [comment]
Cool, I'll get myself a key and try to verify the full flow.

**Comment by onelson** [comment]
OK. Working through some of the missing parts now.
Having trouble getting dotenv to actually populate variables - think this will require using webpack.DefinePlugin to essentially take the runtime value and write it into the generated source.

If I set the twitch key data in my shell, it seems to propagate through to where it needs to be.

Also need to figure out the correct url for the react html page to finish up the flow (unsure `/` is correct for this).

Working on it.

**Comment by onelson** [comment]
Closer to working now.

The redirects to `/` are _not correct_ for this setup. Not sure how to get us back to the "front" page from the auth handlers.

**Comment by onelson** [comment]
Feeling like a simpleton, but I reached out to the boilerplate project https://github.com/chentsulin/electron-react-boilerplate/issues/218

Might try some weak-ass debug tactics like trying to enable directory listings or something... or seeing if express has a way to log out router info.

**Comment by mzmiric5** [comment]
just a note, using a single package.json will cause some problems for production level deployment, both by packaging a lot of bloat in the final app as well as causing issues for later use of electron builder for auto update deployments. this is kind of why I told Bryan about the double package.json in the first place

**Comment by onelson** [comment]
@mzmiric5 Got it. We'll see about figuring out how to split the deps up again after the dust settles, I guess.

By adding an explicit route for `/` which just just does a `res.sendFile()` the oauth flow completes correctly. I'm currently able to see the user data in `/user`, but sadly logout doesn't seem to workout correctly.

I'm trying _really hard_ to wipe the session data, but the auth provider is still seeing me as logged in. After hitting the logout page, then visiting the login page, I'm redirected back to `/` (no input from me) and my data is back in the session.

Not sure where it's reading the data from.

Next on my list will be to have the HomePage component reach out to `/user` to populate the store with user data in the react app. I'll trust we'll figure out the logout issue in time.

**Comment by mzmiric5** [comment]
I still think it might be worth it to look into using React isomorphically, as it would be super easy to send all the needed state data using express's render function, rather than having to mess with cookies and sessions. Usually calling a req.logout() will just work. Keep in mind that once you do a logout and then login again, as long as the app hasn't been removed from the twitch connections, it will actually never ask for authorization again since twitch API doesn't provide real logout. Which also means if the app somehow tries to check auth it might be re-logging you in with the system without user interaction

Edit: I have the code for the isomorhpic (universal) stuff somewhere here, but got a lot of things going on. If you are around on Friday, I could post a gist that could help with this. Might just make it simpler to develop further

**Comment by onelson** [comment]
We'd still need intermediate storage to make isomorphic work - twitch auth flow redirect would have us lose state, right? Unless the callback page is the one that renders the react app, and we also never navigate away from it...

The `req.logout()` not working is making me look suspiciously at the custom db code in here. When we setup the express app, we're telling it 

```
app.use(cookieParser());
app.use(cookieSession({ secret: 'shiver' }));

app.use(passport.initialize());
app.use(passport.session());
```

which makes me think that it'll look to leverage session, but then later we configure the twitch strategy, we write the user info to a db. Not seeing anywhere where we clear the db so maybe that's what is getting stale.

**Comment by mzmiric5** [comment]
@onelson right the idea here is that you keep the state on the express part of the app, and so even when you navigate away from the react app to twitch auth and back to the callback (which should pass the new data to the express part of the app), the express part of the app should then consume the new data, update the state and redirect back to the react app which has again been server side rendered with the new state essentially looking like nothing happened other than a user login/logout.

Because the express app will be serving only a single user in this case since it's a local app, we wouldn't even need to do anything super special to keep track of the state other than use express's session system. If we really needed to do external state tracking, the twitch api does carry over state, so you can pass a database id or a reference as part of the auth request and that same state data will be returned back as part of the callback

**Comment by onelson** [comment]
Alrighty. This branch is "stable." It runs, at least.

I had to make some tweaks to the webpack setup to get things building correctly. Apparently when the build target is `electron-render` it breaks a bunch of packages (namely request, request-promise, superagent -- all of them). Switching to `node` for the target makes it work, for now. Not sure what this will mean for the bundle/package process.

As for the auth... everything appears to be functioning correctly. User data is being written to the db, and I'm deleting the db record on `/logout` but it seems to not really matter that much since passport is storing the oauth token someplace and it never gets cleared from what I can tell. 

As @mzmiric5 pointed out, I can disconnect my account from the app to force a logout, and that's fine, but it would be nice to let the user initiate this from the app. Will need to figure out how to clear that token in `/logout` for this.

Not sure it matters, but the db is not really needed at this point since the react app is being served directly from the express server, so session should be sufficient for persistence.

greeter component knows who I am

**Comment by mzmiric5** [comment]
I still don't get what is causing the problem with passport as I've just tested it on a number of my apps using twitch login and they all work just fine in terms of logging out. They just terminate the connection on the app side and not on twitch side (which is ok, coz clicking login and entering auth data will just skip the authorize step next time). No need to delete the user data from the database, especially if we ever want to keep any user specific preferences that you might want to preserve in a multi user environment....

**Comment by onelson** [comment]
Yeah, I dunno. Obviously the token is the thing that is keeping the identity alive, not the db content. Not sure what's wired wrong, but maybe someone who's worked with passport can take a look at the code.

**Comment by onelson** [comment]
Actually, come to think of it, I must have wired passport in completely wrong no matter what. When I first started playing with this branch `req.user` was never populated; I had to fish out the user data from `req.session.passport` which in my mind should have been abstracted away, right?

**Comment by onelson** [comment]
We did it! Logout is working! Thanks @mzmiric5! 62f338a is watching the requests the electron client makes and clears the cookies when it sees us reach out for `http://localhost:3030/logout`.

The only big change I'd make outside of all the other big changes I've already made would be to really push for having the express app be it's own thing. I don't think there's any need to bundle it at all, and this should really be a multi-user dedicated webservice. Either that, or we could give up using passport and negotiate the oauth from electron without an express app at all. Have the user login at twitch in the electron app, and we should be able to sniff the cookies from the twitch domain...

I'm not sure what y'all had planned for the express app - if it's just there for auth, I think we can simplify and drop it (with a little more dev).

**Comment by mzmiric5** [comment]
Well I'm not sure how much @bryanveloso would want it to be an externally hosted service (I think we mentioned this briefly during one of the hardly working Wednesdays) since well, hosting a node app costs money, and the costs would increase as the userbase for the app would grow, and considering that the app is free, he would have to cover the costs completely, so probably not ideal.

As for shipping express with the app I don't really see the issue with it, but again depends on what Bryan would want to do with it. Obviously if we actually used isomorphic approach for the app, express would be more useful and the whole state management would be simpler since the React app would only care about the data provided to it by express. So it's up to Bryan how he wants to do this. 

Also I'm still not sure why express and electron are separate processes now, usually it's quite feasible to just use electron to run express within it's worker process and that way you can easily control things like electron's cache from within the express app.

**Comment by onelson** [comment]
I'm still reaching because I don't know what happens next, but
- If we are able to request data from twitch directly from the react side, and
- we have all the info we need to do this in the cookie .twitch.tv sets during auth, then
- we maybe don't need the express app at all

If twitch doesn't handle CORS on their API endpoints, then that's another story. We'd need non-browser code to run those requests, but maybe we can do this in the electron code. CORS is usually only a concern from inside the the browser sandbox.

So, my question to you guys is: with auth completed, what info is required to get data from twitch, and how do you normally make those requests?

Here's the data set in the twitch cookie:
`["unique_id", "bits_sudo", "persistent", "api_token", "login", "name", "last_login", "_twitch_session_id"]`
Remember this data is associated with the `'.twitch.tv'` domain so that means it gets set before the callback url is requested. We could set the callback to http://example.com and just not use it.

**Comment by onelson** [comment]
Pretty happy with this iteration. Getting closer to something that makes sense to me.
Will really simplify the distribution of the app to not have to bind to a port. 
- Express app is now only driving hot reload (which was the intended use case from the boilerplate).
- Dropped using passport for auth, instead using `twitch-sdk` (which specifically has hooks for electron).
- Gave up superagent/request since all my http is happening through `Twitch.api()` now.

**Comment by bryanveloso** [comment]
> Well I'm not sure how much @bryanveloso would want it to be an externally hosted service (I think we mentioned this briefly during one of the hardly working Wednesdays) since well, hosting a node app costs money, and the costs would increase as the userbase for the app would grow, and considering that the app is free, he would have to cover the costs completely, so probably not ideal.

Just to address this, I would not want an externally hosted service. The less things that can fail, the better.

**Comment by onelson** [comment]
Cool! 7a1d0ed should help with reducing points of failure but removing the need to bind to a port ;)

**Comment by onelson** [comment]
Prototyped a little component to list live streams on followed channels



I had to wait for @bryanveloso to come online to confirm it worked, though. Heh.

**Comment by bryanveloso** [comment]
Oh nice! 💥

**Comment by onelson** [comment]
I can't remember what the v2 ui looked like so I guess I'm just going to continue with the plumbing.

I guess I'll stitch in a timer to refresh the list in "real time" (we'll be polling, basically). When new stuff appears in the list, I guess I can send a notification to the system tray icon or something.

**Comment by bryanveloso** [comment]
This is in a great place, let's merge it and move on with more awesome stuff. 💥 

Thanks @onelson and @mzmiric5!

**Pull request merged**
